In [ ]:
# **Projet Sciences des données :**<br> Système intelligent de prévision des ventes en grande distribution

### Dataset : **Walmart Sales Forecast**

**Problématique :**<br>
Comment concevoir un système intelligent capable de produire des prévisions fiables et exploitables des ventes hebdomadaires  
par magasin et par département afin d'améliorer la prise de décision opérationnelle ?


**Objectif général :**<br>
Développer un modèle prédictif robuste permettant d’anticiper les ventes hebdomadaires avec un haut niveau de précision.

**Objectifs spécifiques :**
- Analyser les facteurs influençant les ventes
- Construire un pipeline de données fiable
- Tester plusieurs modèles de Machine Learning
- Évaluer les performances
- Déployer un prototype utilisable par les décideurs

## 1. Compréhension des données

### Chargement des données

In [19]:
# Importation des bibliothèques nécessaires
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from IPython.display import display

In [20]:
# Chargement des des données
features = pd.read_csv("Walmart/features.csv")
stores = pd.read_csv("Walmart/stores.csv")
train = pd.read_csv("Walmart/train.csv")
test = pd.read_csv("Walmart/test.csv")

display(features.head())
display(stores.head())
display(train.head())
display(test.head())

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

### Description des variables
| Variable | Description |
|---|---|
| Store | Numéro de magasin |
| Date | Semaine |
| Temperature  | Température moyenne dans la région |
| ... | ... |

In [21]:
# Variables numériques
df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
Store,421570.0,22.20,12.79,1.00,11.00,22.00,33.00,45.00
Dept,421570.0,44.26,30.49,1.00,18.00,37.00,74.00,99.00
Weekly_Sales,421570.0,15981.26,22711.18,-4988.94,2079.65,7612.03,20205.85,693099.36
Temperature,421570.0,60.09,18.45,-2.06,46.68,62.09,74.28,100.14
Fuel_Price,421570.0,3.36,0.46,2.47,2.93,3.45,3.74,4.47
MarkDown1,150681.0,7246.42,8291.22,0.27,2240.27,5347.45,9210.90,88646.76
MarkDown2,111248.0,3334.63,9475.36,-265.76,41.60,192.00,1926.94,104519.54
MarkDown3,137091.0,1439.42,9623.08,-29.10,5.08,24.60,103.99,141630.61
MarkDown4,134967.0,3383.17,6292.38,0.22,504.22,1481.31,3595.04,67474.85
MarkDown5,151432.0,4628.98,5962.89,135.16,1878.44,3359.45,5563.80,108519.28
CPI,421570.0,171.20,39.16,126.06,132.02,182.32,212.42,227.23
Unemployment,421570.0,7.96,1.86,3.88,6.89,7.87,8.57,14.31
Size,421570.0,136727.92,60980.58,34875.00,93638.00,140167.00,202505.00,219622.00

In [ ]:
print("v1")